[package]
edition = "2021"
name = "hiq_fetch"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["lib", "staticlib", "cdylib"]

[dependencies]
async-trait = "0.1.58"
calamine = "0.19.1"
chrono = {version = "0.4.23", features = ["serde"]}
hiq_common = {path = "../common"}
js-sandbox = "0.1.6"
once_cell = "1.16.0"
reqwest = {version = "0.11.12", features = ["blocking", "json", "cookies", "gzip"]}
serde = {version = "1.0.147", features = ["derive"]}
serde_json = "1.0.87"
thiserror = "1.0.37"

[dev-dependencies]
tokio = {version = "1.21.2", features = ["full"]}
